### ISSUE TITLE
[Feature] Separate commands for increasing and decreasing blockquote

### ISSUE THREAD

**Issue by huyz** [Sean10/vscode-markdown-quote#1]
Could you implement the same functionality as https://github.com/czottmann/obsidian-blockquote-levels with two separate commands so that there's no ambiguity?

I explained my rationale here: https://github.com/yzhang-gh/vscode-markdown/pull/811#issuecomment-2028819880

**Comment by Sean10** [comment]
You're right. I'll change it later

**Comment by Sean10** [comment]
publish v0.3.0 with increase and decrease quote. But I don't set default keybinding

**Comment by huyz** [comment]
@Sean10 Works great, thank you!
